---
apiVersion: v1
kind: Pod
metadata:
  name: react-app-pod
  labels:
    app: react-app
spec:
  containers:
    - name: react-app
      image: your-dockerhub-username/react-app:latest # Replace with your Docker Hub image
      ports:
        - containerPort: 3000
      env:
        - name: NODE_ENV
          value: "production"
